// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Gameplay.Items.Recipes;
	
    [Serialized]
    [LocDisplayName("Raw Limestone")]
    [MaxStackSize(10)]
    [Weight(30000)]
    [Tag("Constructable")]
    [Tag("RawStone")]
    public partial class RawLimestoneItem : BlockItem<LimestoneBlock>
    {
        public override LocString DisplayNamePlural { get { return Localizer.DoStr("Raw Limestone"); } }
    }
	
    [RequiresSkill(typeof(MiningSkill), 5)]
    public partial class RawLimestoneRecipe : RecipeFamily
    {
        public RawLimestoneRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                "RawLimestone",  //noloc
                Localizer.DoStr("Raw Limestone"),
                new List<IngredientElement>
                {
                    new IngredientElement(typeof(LimestoneItem), 6, true),
                    new IngredientElement(typeof(MortarItem), 2, typeof(MiningSkill)),
                },
                new List<CraftingElement>
                {
                    new CraftingElement<RawLimestoneItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(MiningSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(RawLimestoneRecipe), .25f, typeof(MiningSkill));
			
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Raw Limestone"), typeof(RawLimestoneRecipe));
            this.ModsPostInitialize();
			
            CraftingComponent.AddRecipe(typeof(MasonryTableObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
