// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from RecipeTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Core.Controller;
    using Eco.Gameplay.Settlements.ClaimStakes;
    using Eco.Gameplay.Items.Recipes;

    [RequiresSkill(typeof(GatheringSkill), 1)]
    public partial class CrushBullRushRecipe : RecipeFamily
    {
        public CrushBullRushRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "CrushBullRush",  //noloc
                displayName: Localizer.DoStr("Crush Bullrush"),

                // Defines the ingredients needed to craft this recipe.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(BullRushItem), 12, typeof(GatheringSkill)),
                },

                // Defines our recipe output items.
                items: new List<CraftingElement>
                {
                    new CraftingElement<BullRushPulpItem>(1),
                });

            this.Recipes = new List<Recipe> { recipe };

            this.ExperienceOnCraft = 0.5f;

            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(30, typeof(GatheringSkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(
                beneficiary: typeof(CrushBullRushRecipe),
                start: 0.5f,
                skillType: typeof(GatheringSkill));

            // Perform pre/post initialization for user mods
            this.ModsPreInitialize();
            this.Initialize(
                displayText: Localizer.DoStr("Crush Bullrush"),
                recipeType: typeof(CrushBullRushRecipe));

            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system
            CraftingComponent.AddRecipe(
                tableType: typeof(FiberScutchingStationObject),
                recipeFamily: this);
        }

        /// <summary>
        /// Hook for mods to customize RecipeFamily before initialization.
        /// You can change recipes, XP, labor, and time here.
        /// </summary>
        partial void ModsPreInitialize();

        /// <summary>
        /// Hook for mods to customize RecipeFamily after initialization,
        /// but before registration.
        /// </summary>
        partial void ModsPostInitialize();
    }
}