// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from SeedTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Gameplay.Blocks;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Items.SearchAndSelect;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Players;
    using System.ComponentModel;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;

    [RequiresSkill(typeof(FarmingSkill), 1)]
    [Ecopedia("Food", "Seed", subPageName: "Bullrush Seed Item")]
    public partial class BullRushSeedRecipe : RecipeFamily
    {
        public BullRushSeedRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(name: "BullRushSeed", displayName: Localizer.DoStr("Bullrush Seed"),

                // Defines the ingredients needed to craft this recipe.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(BullRushItem), 3, typeof(FarmingSkill)),
                },

                garbages: new List<GarbageOutput>
                {
                },

                // Define our recipe output items.
                items: new List<CraftingElement>{new CraftingElement<BullrushSeedItem>(6)});

            this.Recipes = new List<Recipe> { recipe };

            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(60, typeof(FarmingSkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(BullRushSeedRecipe), start: 0.2f, skillType: typeof(FarmingSkill));

            // Perform pre/post initialization for user mods
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Bullrush Seed"), recipeType: typeof(BullRushSeedRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system
            CraftingComponent.AddRecipe(tableType: typeof(FarmersTableObject),recipeFamily: this);
        }

        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}