// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from ItemTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Gameplay.Blocks;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Items.SearchAndSelect;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Players;
    using System.ComponentModel;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
	
	
	public partial class SoilSamplerRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(TallowCandleRecipe));
		}
    }

    public partial class BeetSugarRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(SimpleSyrupRecipe));
		}
    }
	
	public partial class ProcessedBeetSugarRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(SimpleSyrupRecipe));
		}
    }
	
	
	public partial class ProcessedFishOilRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(FishOilRecipe));
		}
    }
	
	public partial class LimestoneOtterStatueRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(SandConcentrateRecipe));
		}
    }
	
	public partial class ElkStatuetteRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(HarePeltRecipe));
		}
    }
	
	public partial class DecorativeAnchorRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(WoodenBargeRecipe));
		}
    }
	
	public partial class DecorativeShipWheelRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(SteelMooragePostRecipe));
			this.Recipes[0].Ingredients.Add(new IngredientElement(typeof(ShipWaxItem), 3, true));
		}
    }
	
	
	// public partial class BluePowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class CharcoalPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class CopperHydroxideRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class CyanPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class IronOxideRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class MagentaPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class WhitePowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class YellowPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class PowderedCreosoteRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	// public partial class ColoredPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(BasePaintRecipe));
	// 	}
    // }
	
	// public partial class ProcessedBluePowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedCharcoalPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedCopperHydroxideRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedCyanPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedIronOxideRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedMagentaPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedWhitePowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedYellowPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedCreosoteRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
	// public partial class ProcessedColoredPowderRecipe
    // {
    //     partial void ModsPostInitialize()
	// 	{
	// 		this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(InkRecipe));
	// 	}
    // }
    
}