// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />


namespace EcoPulse.StatueMod
{
    using Eco.Core.Controller;
    using Eco.Core.Items;
    using Eco.Core.Utils;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Civics.Objects;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.Components.Storage;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Housing.PropertyValues;
    using Eco.Gameplay.Interactions;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Occupancy;
    using Eco.Gameplay.Pipes;
    using Eco.Gameplay.Pipes.Gases;
    using Eco.Gameplay.Pipes.LiquidComponents;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.NewTooltip;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared;
    using Eco.Shared.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Math;
    using Eco.Shared.Networking;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.World.Blocks;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Numerics;
    using static Eco.Gameplay.Housing.PropertyValues.HomeFurnishingValue;


    [Serialized]
    [RequireComponent(typeof(PropertyAuthComponent))]
    [RequireComponent(typeof(HousingComponent))]
    [RequireComponent(typeof(OccupancyRequirementComponent))]
    [RequireComponent(typeof(ForSaleComponent))]
    [Tag("Usable")]
    [Ecopedia("Housing Objects", "Outdoor", subPageName: "Wooden Penguin Statue Item")]
    public partial class WoodenPenguinStatueObject : WorldObject, IRepresentsItem
    {
        public virtual Type RepresentedItemType => typeof(WoodenPenguinStatueItem);
        public override LocString DisplayName => Localizer.DoStr("Wooden Penguin Statue");
        public override TableTextureMode TableTexture => TableTextureMode.Wood;

        protected override void Initialize()
        {
            this.ModsPreInitialize();
            this.GetComponent<HousingComponent>().HomeValue = WoodenPenguinStatueItem.homeValue;
            this.ModsPostInitialize();
        }

        static WoodenPenguinStatueObject()
        {
            WorldObject.AddOccupancy<WoodenPenguinStatueObject>(PenguinStatue.GetOccupency());

        }

        /// <summary>Hook for mods to customize WorldObject before initialization. You can change housing values here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize WorldObject after initialization.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Wooden Penguin Statue")]
    [LocDescription("Wooden penguin meticulously carved from a sturdy log - it won't melt in the sun, but still prefers the shade.")]
    [Ecopedia("Housing Objects", "Outdoor", createAsSubPage: true)]
    [Tag("Housing")]
    [Weight(5000)] // Defines how heavy WoodenPenguinStatue is.
    public partial class WoodenPenguinStatueItem : WorldObjectItem<WoodenPenguinStatueObject>
    {
        protected override OccupancyContext GetOccupancyContext => new SideAttachedContext(0 | DirectionAxisFlags.Down, WorldObject.GetOccupancyInfo(this.WorldObjectType));
        public override HomeFurnishingValue HomeValue => homeValue;
        public static readonly HomeFurnishingValue homeValue = new HomeFurnishingValue()
        {
            ObjectName = typeof(WoodenPenguinStatueObject).UILink(),
            Category = HousingConfig.GetRoomCategory("Outdoor"),
            BaseValue = 3,
            TypeForRoomLimit = Localizer.DoStr("Statue"),
            DiminishingReturnMultiplier = 0.1f

        };

    }

    /// <summary>
    /// <para>Server side recipe definition for "WoodenPenguinStatue".</para>
    /// <para>More information about RecipeFamily objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Items.RecipeFamily.html</para>
    /// </summary>
    /// <remarks>
    /// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
    /// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
    /// </remarks>
    [RequiresSkill(typeof(CarpentrySkill), 6)]
    [ForceCreateView]
    [Ecopedia("Housing Objects", "Outdoor", subPageName: "Wooden Penguin Statue Item")]
    public partial class WoodenPenguinStatueRecipe : Recipe
    {
        public WoodenPenguinStatueRecipe()
        {
            this.Init(
                name: "WoodenPenguinStatue",  //noloc
                displayName: Localizer.DoStr("Wooden Penguin Statue"),

                // Defines the ingredients needed to craft this recipe. An ingredient items takes the following inputs
                // type of the item, the amount of the item, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement("HewnLog", 30, typeof(CarpentrySkill)),
                    new IngredientElement(typeof(PrimitiveResinItem), 5, true),
                    new IngredientElement(typeof(PedestalItem), 1, true),
                },

                // Define our recipe output items.
                // For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<WoodenPenguinStatueItem>()
                });

            this.ModsPostInitialize();
            CraftingComponent.AddTagProduct(typeof(CarpentryTableObject), typeof(WoodenLionStatueRecipe), this);
        }

        /// <summary>Hook for mods to customize Recipe after initialization.</summary>
        partial void ModsPostInitialize();
    }

}
