// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from PluginModuleTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;
    using Eco.Gameplay.Bonuses;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>

    /// <summary>
    /// <para>Server side recipe definition for "BasicUpgrade".</para>
    /// <para>More information about RecipeFamily objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Items.RecipeFamily.html</para>
    /// </summary>
    /// <remarks>
    /// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
    /// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
    /// </remarks>
    [RequiresSkill(typeof(SelfImprovementSkill), 1)]
    [Ecopedia("Upgrade Modules", "Basic Upgrades", subPageName: "Basic Upgrade Item")]
    public partial class BasicUpgradeRecipe : RecipeFamily
    {
        public BasicUpgradeRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "BasicUpgrade",  //noloc
                displayName: Localizer.DoStr("Basic Upgrade"),

                // Defines the ingredients needed to craft this recipe. An ingredient items takes the following inputs
                // type of the item, the amount of the item, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(DendrologyResearchPaperAdvancedItem), 2, true),
                    new IngredientElement(typeof(GatheringResearchPaperBasicItem), 2, true),
                    new IngredientElement(typeof(AgricultureResearchPaperBasicItem), 1, true),
                    new IngredientElement("Basic Research", 5, true), //noloc
                },
                garbages: new List<GarbageOutput>
                {
                    new GarbageOutput(typeof(Trash), 0.2f),
                },
                // Define our recipe output items.
                // For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<BasicUpgradeItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 1; // Defines how much experience is gained when crafted.

            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(1500,typeof(SelfImprovementSkill));


            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(BasicUpgradeRecipe), start: 4, skillType: typeof(SelfImprovementSkill));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Basic Upgrade"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Basic Upgrade"), recipeType: typeof(BasicUpgradeRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(ResearchTableObject), recipeFamily: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Basic Upgrade")]
    [LocDescription("Basic Upgrade that increases crafting efficiency.")]
    [Weight(1000)]
    [SalvageCost(typeof(Trash), 1.0f)]
    [Ecopedia("Upgrade Modules", "Basic Upgrades", createAsSubPage: true)]                                                                      //_If_EcopediaPage_
    [Tag("Upgrade")]
    [Tag("BasicModule")]
    public partial class BasicUpgradeItem :
        EfficiencyModule
    {
        public override LocString DisplayNamePlural { get { return Localizer.DoStr("Basic Upgrades"); } }

        public BasicUpgradeItem() : base(ModuleTypes.None, 1f) { }

		public override float MaterialTierBump => 0.4f;
        public override float PowerConsumption => 0f;
        public override ModulePowerType PowerType => ModulePowerType.None;

        public override IEnumerable<Bonus> Bonuses => new[]
        {
            new Bonus
            {
                Causes  = new List<BonusCause>  { new CraftBonusCause { Action = BonusAction.ResourceCost } },
                Effects = new List<BonusEffect> { new BonusEffectAdditivePercent { Percent = -0.2f, LowerIsBetter = true  } },
            },
        };
    }
}
