﻿// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using Eco.Gameplay.Blocks;
    using Eco.Shared.Localization;
    using Eco.World.Blocks;

    public partial class ArchTopCenterFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "ArchTopCenter";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("Arch Top Center");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("Arch Top Center");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(MortaredArchesFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 3;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    public partial class ArchTopSideFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "ArchTopSide";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("Arch Top Side");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("Arch Top Side");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(MortaredArchesFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 2;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    public partial class ArchSideFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "ArchSide";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("Arch Side");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("Arch Side");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(MortaredArchesFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 1;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

}
