﻿// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using Eco.Gameplay.Blocks;
    using Eco.Shared.Localization;
    using Eco.World.Blocks;

    public partial class Corner45FormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "Corner45";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("45 Degree Corner");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("45 Degree Corner");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(FortyFiveFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 1;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    public partial class CornerSmall45FormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "CornerSmall45";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("45 Degree Small Corner");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("45 Degree Small Corner");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(FortyFiveFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 2;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    public partial class FourtyFiveWallFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "FourtyFiveWall";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("45 Wall");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("45 Wall");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(FortyFiveFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 1;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    public partial class Roof45FormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "Roof45";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("45 Degree Roof Corner");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("45 Degree Roof Corner");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(FortyFiveFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 3;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

}
