// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FormsTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Water;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Tag = Eco.Core.Items.TagAttribute;
    using Eco.World.Color;

    //Custom Forms
    //45
    [RotatedVariants(typeof(MortaredSandstoneFourtyFiveBlock), typeof(MortaredSandstoneFourtyFive90Block), typeof(MortaredSandstoneFourtyFive180Block), typeof(MortaredSandstoneFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(Corner45FormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Small45
    [RotatedVariants(typeof(MortaredSandstoneSmallFourtyFiveBlock), typeof(MortaredSandstoneSmallFourtyFive90Block), typeof(MortaredSandstoneSmallFourtyFive180Block), typeof(MortaredSandstoneSmallFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(CornerSmall45FormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneSmallFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneSmallFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneSmallFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneSmallFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //45 Wall
    [RotatedVariants(typeof(MortaredSandstoneFourtyFiveWallBlock), typeof(MortaredSandstoneFourtyFiveWall90Block), typeof(MortaredSandstoneFourtyFiveWall180Block), typeof(MortaredSandstoneFourtyFiveWall270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(FourtyFiveWallFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneFourtyFiveWallBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneFourtyFiveWall90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneFourtyFiveWall180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneFourtyFiveWall270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Roof45
    [RotatedVariants(typeof(MortaredSandstoneRoofFourtyFiveBlock), typeof(MortaredSandstoneRoofFourtyFive90Block), typeof(MortaredSandstoneRoofFourtyFive180Block), typeof(MortaredSandstoneRoofFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(Roof45FormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Ramps
    [RotatedVariants(typeof(MortaredSandstoneRampABlock), typeof(MortaredSandstoneRampA90Block), typeof(MortaredSandstoneRampA180Block), typeof(MortaredSandstoneRampA270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampAFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampABlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampA90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampA180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampA270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredSandstoneRampBBlock), typeof(MortaredSandstoneRampB90Block), typeof(MortaredSandstoneRampB180Block), typeof(MortaredSandstoneRampB270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampBFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampBBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampB90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampB180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampB270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredSandstoneRampCBlock), typeof(MortaredSandstoneRampC90Block), typeof(MortaredSandstoneRampC180Block), typeof(MortaredSandstoneRampC270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampCFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampCBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampC90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampC180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampC270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredSandstoneRampDBlock), typeof(MortaredSandstoneRampD90Block), typeof(MortaredSandstoneRampD180Block), typeof(MortaredSandstoneRampD270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampDFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampDBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampD90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampD180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRampD270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //RoofRamps
    [RotatedVariants(typeof(MortaredSandstoneRoofRampABlock), typeof(MortaredSandstoneRoofRampA90Block), typeof(MortaredSandstoneRoofRampA180Block), typeof(MortaredSandstoneRoofRampA270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampAFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampABlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampA90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampA180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampA270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredSandstoneRoofRampBBlock), typeof(MortaredSandstoneRoofRampB90Block), typeof(MortaredSandstoneRoofRampB180Block), typeof(MortaredSandstoneRoofRampB270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampBFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampBBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampB90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampB180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampB270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredSandstoneRoofRampCBlock), typeof(MortaredSandstoneRoofRampC90Block), typeof(MortaredSandstoneRoofRampC180Block), typeof(MortaredSandstoneRoofRampC270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampCFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampCBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampC90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampC180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampC270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredSandstoneRoofRampDBlock), typeof(MortaredSandstoneRoofRampD90Block), typeof(MortaredSandstoneRoofRampD180Block), typeof(MortaredSandstoneRoofRampD270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampDFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampDBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampD90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampD180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofRampD270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Roof Edge
    [RotatedVariants(typeof(MortaredSandstoneRoofEdgeBlock), typeof(MortaredSandstoneRoofEdge90Block), typeof(MortaredSandstoneRoofEdge180Block), typeof(MortaredSandstoneRoofEdge270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofEdgeFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofEdgeBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofEdge90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofEdge180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneRoofEdge270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //ARCHES
    //TopCenterArch
    [RotatedVariants(typeof(MortaredSandstoneArchTopCenterBlock), typeof(MortaredSandstoneArchTopCenter90Block), typeof(MortaredSandstoneArchTopCenter180Block), typeof(MortaredSandstoneArchTopCenter270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchTopCenterFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchTopCenterBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchTopCenter90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchTopCenter180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchTopCenter270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //TopSideArch
    [RotatedVariants(typeof(MortaredSandstoneArchTopSideBlock), typeof(MortaredSandstoneArchTopSide90Block), typeof(MortaredSandstoneArchTopSide180Block), typeof(MortaredSandstoneArchTopSide270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchTopSideFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchTopSideBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchTopSide90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchTopSide180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchTopSide270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //SideArch
    [RotatedVariants(typeof(MortaredSandstoneArchSideBlock), typeof(MortaredSandstoneArchSide90Block), typeof(MortaredSandstoneArchSide180Block), typeof(MortaredSandstoneArchSide270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchSideFormType), typeof(MortaredSandstoneItem))]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchSideBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchSide90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchSide180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredSandstoneArchSide270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

}