// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    
    /// <summary>
    /// <para>Server side recipe definition for "RoastPumpkinTallow".</para>
    /// <para>More information about RecipeFamily objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Items.RecipeFamily.html</para>
    /// </summary>
    /// <remarks>
    /// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
    /// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
    /// </remarks>
    [RequiresSkill(typeof(BakingSkill), 3)]
    [Ecopedia("Food", "Baking", subPageName: "Roast Pumpkin Item")]
    public partial class RoastPumpkinTallowRecipe : RecipeFamily
    {
        public RoastPumpkinTallowRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "RoastPumpkinTallow",  //noloc
                displayName: Localizer.DoStr("Tallow-Roast Pumpkin"),

                // Defines the ingredients needed to craft this recipe. An ingredient items takes the following inputs
                // type of the item, the amount of the item, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(PumpkinItem), 2,typeof(BakingSkill)),
                    new IngredientElement(typeof(SugarItem), 2,typeof(BakingSkill)),
					new IngredientElement(typeof(TallowItem), 1,typeof(BakingSkill)),
                },
                // Define our recipe output items.
                // For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<RoastPumpkinItem>(2)
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 1; // Defines how much experience is gained when crafted.

            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(25,typeof(BakingSkill));
			
			// Defines if a recipe requires a talent or not , and if so which one.
            this.RequiresTalentUnlock = true;



            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(RoastPumpkinTallowRecipe), start: 2, skillType: typeof(BakingSkill));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Roast Pumpkin"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Tallow-Roast Pumpkin"), recipeType: typeof(RoastPumpkinTallowRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(BakeryOvenObject), recipeFamily: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
