// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from ItemTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Gameplay.Blocks;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Items.SearchAndSelect;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Players;
    using System.ComponentModel;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

        

    public partial class TomatoSeedRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(TallowCandleRecipe));
			// Defines if a recipe requires a talent or not , and if so which one.
            this.RequiresTalentUnlock = true;
		}
    }
	
	public partial class PricklyPearSeedRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(TallowCandleRecipe));
			// Defines if a recipe requires a talent or not , and if so which one.
            this.RequiresTalentUnlock = true;
		}
    }
	
	public partial class PineappleSeedRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(TallowCandleRecipe));
			// Defines if a recipe requires a talent or not , and if so which one.
            this.RequiresTalentUnlock = true;
		}
    }
	
	public partial class PapayaSeedRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(TallowCandleRecipe));
			// Defines if a recipe requires a talent or not , and if so which one.
            this.RequiresTalentUnlock = true;
		}
    }
	
	public partial class HuckleberrySeedRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(TallowCandleRecipe));
			// Defines if a recipe requires a talent or not , and if so which one.
            this.RequiresTalentUnlock = true;
		}
    }
	
	public partial class CottonSeedRecipe
    {
        partial void ModsPostInitialize()
		{
			this.RequiredSkills = RequiresSkillAttribute.Cache.Get(typeof(TallowCandleRecipe));
			// Defines if a recipe requires a talent or not , and if so which one.
            this.RequiresTalentUnlock = true;
		}
    }

    
}