// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from ToolTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Items.Internal;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Shared.Math;
    using Eco.Core.Controller;
    using Eco.Gameplay.Interactions.Interactors;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;

    [RequiresModule(typeof(AnvilObject))]
    [RequiresSkill(typeof(BlacksmithSkill), 1)]
    [Ecopedia("Items", "Tools", subPageName: "Iron Pickaxe Item")]
    public partial class IronPickaxeRecipe : RecipeFamily
    {
        public IronPickaxeRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "IronPickaxe",
                displayName: Localizer.DoStr("Iron Pickaxe"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(IronBarItem), 12,typeof(BlacksmithSkill)),
                    new IngredientElement(typeof(LeatherHideItem), 8,typeof(BlacksmithSkill)),
                    new IngredientElement("WoodBoard", 12,typeof(BlacksmithSkill)),
                },
                garbages: new List<GarbageOutput> { },
                items: new List<CraftingElement>
                {
                    new CraftingElement<IronPickaxeItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 0.5f;
            this.LaborInCalories = CreateLaborInCaloriesValue(250,typeof(BlacksmithSkill));
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(IronPickaxeRecipe), start: 0.5f, skillType: typeof(BlacksmithSkill));
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Iron Pickaxe"), recipeType: typeof(IronPickaxeRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(tableType: typeof(GrindstoneObject), recipeFamily: this);
        }

        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Iron Pickaxe")]
    [LocDescription("A sturdy iron pickaxe used to break down stone and ore into usable rubble.")]
    [Tier(2)]
    [RepairRequiresSkill(typeof(BlacksmithSkill), 0)]
    [Weight(1000)]
    [SalvageCost(typeof(WoodScrap), 1.0f, typeof(IronScrap), 4.0f, typeof(BioResidue), 1.0f)]
    [Category("Tool")]
    [Tag("Tool")]
    [Ecopedia("Items", "Tools", createAsSubPage: true)]
    public partial class IronPickaxeItem : PickaxeItem
    {
        private static IDynamicValue caloriesBurn = CreateCalorieValue(20, typeof(MiningSkill), typeof(IronPickaxeItem));
        private static IDynamicValue damage = new MultiDynamicValue(MultiDynamicOps.Sum,
            new TalentModifiedValue(typeof(IronPickaxeItem), typeof(MiningToolEfficiencyTalent), 0),
            new TalentModifiedValue(typeof(IronPickaxeItem), typeof(MiningToolStrengthTalent), 0),
            new ConstantValue(2));
        private static IDynamicValue exp = new ConstantValue(0.1f);
        private static IDynamicValue tier = new ConstantValue(2);
        private static IDynamicValue perkDamage = new MultiDynamicValue(MultiDynamicOps.Sum,
            new ConstantValue(0),
            new TalentModifiedValue(typeof(IronPickaxeItem), typeof(MiningToolEfficiencyTalent), 0),
            new TalentModifiedValue(typeof(IronPickaxeItem), typeof(MiningToolStrengthTalent), 0));
        private static SkillModifiedValue skilledRepairCost = new SkillModifiedValue(2, BlacksmithSkill.MultiplicativeStrategy, typeof(BlacksmithSkill), typeof(IronPickaxeItem), Localizer.DoStr("repair cost"), DynamicValueType.Efficiency);

        public override IDynamicValue CaloriesBurn => caloriesBurn;
        public override IDynamicValue Damage => damage;
        public override Type ExperienceSkill => typeof(MiningSkill);
        public override IDynamicValue ExperienceRate => exp;
        public override IDynamicValue PerkDamage => perkDamage;
        public override IDynamicValue Tier => tier;
        public override IDynamicValue SkilledRepairCost => skilledRepairCost;
        public override float OriginalMaxDurability => 1000f;
        public override int FullRepairAmount => 2;

        public override IEnumerable<RepairingItem> RepairItems { get
        {
            yield return RepairingItem.Resolve("CoarseStone", 2);
            yield return RepairingItem.Resolve("SharpeningSteel", 1);
            yield return RepairingItem.Resolve("Whetstone", 2);
            yield return RepairingItem.Resolve("PolishingPaste", 0.5f);
        } }
    }
}
