// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from ToolTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Items.Internal;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Shared.Math;
    using Eco.Core.Controller;
    using Eco.Gameplay.Interactions.Interactors;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;


    [RequiresModule(typeof(BlacksmithTableObject))]
    [RequiresSkill(typeof(BlacksmithSkill), 5)]
    [Ecopedia("Items", "Tools", subPageName: "Modern Pickaxe Item")]
    public partial class ModernPickaxeRecipe : RecipeFamily
    {
        public ModernPickaxeRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "ModernPickaxe",
                displayName: Localizer.DoStr("Modern Pickaxe"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(FiberglassItem), 20,typeof(BlacksmithSkill)),
                    new IngredientElement(typeof(SteelBarItem), 25,typeof(BlacksmithSkill)),
                    new IngredientElement(typeof(SyntheticRubberItem), 2,typeof(BlacksmithSkill)),
                },
                garbages: new List<GarbageOutput> { },
                items: new List<CraftingElement>
                {
                    new CraftingElement<ModernPickaxeItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 0.5f;
            this.LaborInCalories = CreateLaborInCaloriesValue(1000,typeof(BlacksmithSkill));
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(ModernPickaxeRecipe), start: 0.5f, skillType: typeof(BlacksmithSkill));
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Modern Pickaxe"), recipeType: typeof(ModernPickaxeRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(tableType: typeof(PowerHammerObject), recipeFamily: this);
        }

        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Modern Pickaxe")]
    [LocDescription("A modern pickaxe with a non-slip handle made using fiberglass.")]
    [Tier(4)]
    [RepairRequiresSkill(typeof(BlacksmithSkill), 0)]
    [Weight(1000)]
    [SalvageCost(typeof(PlasticScrap), 3.0f, typeof(IronScrap), 5.0f, typeof(ChemicalWaste), 0.2f)]
    [Category("Tool")]
    [Tag("Tool")]
    [Ecopedia("Items", "Tools", createAsSubPage: true)]
    public partial class ModernPickaxeItem : PickaxeItem
    {
        private static IDynamicValue caloriesBurn = CreateCalorieValue(20, typeof(MiningSkill), typeof(ModernPickaxeItem));
        private static IDynamicValue damage = new MultiDynamicValue(MultiDynamicOps.Sum,
            new TalentModifiedValue(typeof(ModernPickaxeItem), typeof(MiningToolEfficiencyTalent), 0),
            new TalentModifiedValue(typeof(ModernPickaxeItem), typeof(MiningToolStrengthTalent), 0),
            new ConstantValue(4));
        private static IDynamicValue exp = new ConstantValue(0.1f);
        private static IDynamicValue tier = new ConstantValue(4);
        private static IDynamicValue perkDamage = new MultiDynamicValue(MultiDynamicOps.Sum,
            new ConstantValue(0),
            new TalentModifiedValue(typeof(ModernPickaxeItem), typeof(MiningToolEfficiencyTalent), 0),
            new TalentModifiedValue(typeof(ModernPickaxeItem), typeof(MiningToolStrengthTalent), 0));
        private static SkillModifiedValue skilledRepairCost = new SkillModifiedValue(2, BlacksmithSkill.MultiplicativeStrategy, typeof(BlacksmithSkill), typeof(ModernPickaxeItem), Localizer.DoStr("repair cost"), DynamicValueType.Efficiency);

        public override IDynamicValue CaloriesBurn => caloriesBurn;
        public override IDynamicValue Damage => damage;
        public override Type ExperienceSkill => typeof(MiningSkill);
        public override IDynamicValue ExperienceRate => exp;
        public override IDynamicValue PerkDamage => perkDamage;
        public override IDynamicValue Tier => tier;
        public override IDynamicValue SkilledRepairCost => skilledRepairCost;
        public override float OriginalMaxDurability => 4000f;
        public override int FullRepairAmount => 2;

        public override IEnumerable<RepairingItem> RepairItems { get
        {
            yield return RepairingItem.Resolve("CoarseStone", 2);
            yield return RepairingItem.Resolve("SharpeningSteel", 1);
            yield return RepairingItem.Resolve("Whetstone", 2);
            yield return RepairingItem.Resolve("PolishingPaste", 0.5f);
        } }
    }
}
