// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />
namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Interactions;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Occupancy;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared;
    using Eco.Shared.Math;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.Shared.Items;
    using Eco.Shared.Networking;
    using Eco.Gameplay.Pipes;
	using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Housing.PropertyValues;
    using Eco.Gameplay.Systems.NewTooltip;
    using Eco.Core.Controller;
    using Eco.Core.Utils;
	using Eco.Gameplay.Components.Storage;
    using static Eco.Gameplay.Housing.PropertyValues.HomeFurnishingValue;
    using Eco.Gameplay.Items.Recipes;
    
    [Serialized]
    [RequireComponent(typeof(PropertyAuthComponent))]
    [RequireComponent(typeof(CustomTextComponent))]
    [RequireComponent(typeof(HousingComponent))]
    [RequireComponent(typeof(OccupancyRequirementComponent))]
    [Tag("Usable")]
    public partial class BronzeTrophyObject : WorldObject, IRepresentsItem
    {
        public virtual Type RepresentedItemType => typeof(BronzeTrophyItem);
        public override LocString DisplayName => Localizer.DoStr("Bronze Trophy");
        public override TableTextureMode TableTexture => TableTextureMode.Metal;

        protected override void Initialize()
        {
            this.ModsPreInitialize();
            this.GetComponent<CustomTextComponent>().Initialize(300);
            this.GetComponent<HousingComponent>().HomeValue = BronzeTrophyItem.homeValue;
            this.ModsPostInitialize();
        }

        protected override void OnCreatePostInitialize()
        {
            base.OnCreatePostInitialize();
            this.GetComponent<PropertyAuthComponent>().SetPublic();
        }

        /// <summary>Hook for mods to customize WorldObject before initialization. You can change housing values here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize WorldObject after initialization.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Bronze Trophy")]
    [LocDescription("Congratulation! You won a Bronze Trophy!")]
    [Tag("Housing")]
    [Weight(1000)]
	[Tag(nameof(SurfaceTags.CanBeOnSurface))]
    public partial class BronzeTrophyItem : WorldObjectItem<BronzeTrophyObject>, IPersistentData
    {
        [Serialized, SyncToView, NewTooltipChildren(CacheAs.Instance, flags: TTFlags.AllowNonControllerTypeForChildren)] 
        public object PersistentData { get; set; }

        public override bool ShowLocationsInWorld => false;
		protected override OccupancyContext GetOccupancyContext => new SideAttachedContext(
				0 | DirectionAxisFlags.Down, 
				WorldObject.GetOccupancyInfo(this.WorldObjectType)
		);
        public override HomeFurnishingValue HomeValue => homeValue;
        
        public static readonly HomeFurnishingValue homeValue = new HomeFurnishingValue()
        {
            ObjectName = typeof(BronzeTrophyObject).UILink(),
            Category = HousingConfig.GetRoomCategory("Decoration"),
            BaseValue = 3,  // Adjust this value to determine the housing bonus
            TypeForRoomLimit = Localizer.DoStr("Trophy"),  // Creates a category for room limit purposes
            DiminishingReturnMultiplier = 0.7f  // Adjust this to control how multiple trophies affect housing
        };
    }
}