// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FormsTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Water;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Tag = Eco.Core.Items.TagAttribute;
    using Eco.World.Color;

    //Custom Forms
    //45
    [RotatedVariants(typeof(MortaredLimestoneFourtyFiveBlock), typeof(MortaredLimestoneFourtyFive90Block), typeof(MortaredLimestoneFourtyFive180Block), typeof(MortaredLimestoneFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(Corner45FormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Small45
    [RotatedVariants(typeof(MortaredLimestoneSmallFourtyFiveBlock), typeof(MortaredLimestoneSmallFourtyFive90Block), typeof(MortaredLimestoneSmallFourtyFive180Block), typeof(MortaredLimestoneSmallFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(CornerSmall45FormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneSmallFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneSmallFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneSmallFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneSmallFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //45 Wall
    [RotatedVariants(typeof(MortaredLimestoneFourtyFiveWallBlock), typeof(MortaredLimestoneFourtyFiveWall90Block), typeof(MortaredLimestoneFourtyFiveWall180Block), typeof(MortaredLimestoneFourtyFiveWall270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(FourtyFiveWallFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneFourtyFiveWallBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneFourtyFiveWall90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneFourtyFiveWall180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneFourtyFiveWall270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Roof45
    [RotatedVariants(typeof(MortaredLimestoneRoofFourtyFiveBlock), typeof(MortaredLimestoneRoofFourtyFive90Block), typeof(MortaredLimestoneRoofFourtyFive180Block), typeof(MortaredLimestoneRoofFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(Roof45FormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Ramps
    [RotatedVariants(typeof(MortaredLimestoneRampABlock), typeof(MortaredLimestoneRampA90Block), typeof(MortaredLimestoneRampA180Block), typeof(MortaredLimestoneRampA270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampAFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampABlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampA90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampA180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampA270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredLimestoneRampBBlock), typeof(MortaredLimestoneRampB90Block), typeof(MortaredLimestoneRampB180Block), typeof(MortaredLimestoneRampB270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampBFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampBBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampB90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampB180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampB270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredLimestoneRampCBlock), typeof(MortaredLimestoneRampC90Block), typeof(MortaredLimestoneRampC180Block), typeof(MortaredLimestoneRampC270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampCFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampCBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampC90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampC180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampC270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredLimestoneRampDBlock), typeof(MortaredLimestoneRampD90Block), typeof(MortaredLimestoneRampD180Block), typeof(MortaredLimestoneRampD270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampDFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampDBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampD90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampD180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRampD270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //RoofRamps
    [RotatedVariants(typeof(MortaredLimestoneRoofRampABlock), typeof(MortaredLimestoneRoofRampA90Block), typeof(MortaredLimestoneRoofRampA180Block), typeof(MortaredLimestoneRoofRampA270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampAFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampABlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampA90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampA180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampA270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredLimestoneRoofRampBBlock), typeof(MortaredLimestoneRoofRampB90Block), typeof(MortaredLimestoneRoofRampB180Block), typeof(MortaredLimestoneRoofRampB270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampBFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampBBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampB90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampB180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampB270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredLimestoneRoofRampCBlock), typeof(MortaredLimestoneRoofRampC90Block), typeof(MortaredLimestoneRoofRampC180Block), typeof(MortaredLimestoneRoofRampC270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampCFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampCBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampC90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampC180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampC270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredLimestoneRoofRampDBlock), typeof(MortaredLimestoneRoofRampD90Block), typeof(MortaredLimestoneRoofRampD180Block), typeof(MortaredLimestoneRoofRampD270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampDFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampDBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampD90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampD180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofRampD270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Roof Edge
    [RotatedVariants(typeof(MortaredLimestoneRoofEdgeBlock), typeof(MortaredLimestoneRoofEdge90Block), typeof(MortaredLimestoneRoofEdge180Block), typeof(MortaredLimestoneRoofEdge270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofEdgeFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofEdgeBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofEdge90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofEdge180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneRoofEdge270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //ARCHES
    //TopCenterArch
    [RotatedVariants(typeof(MortaredLimestoneArchTopCenterBlock), typeof(MortaredLimestoneArchTopCenter90Block), typeof(MortaredLimestoneArchTopCenter180Block), typeof(MortaredLimestoneArchTopCenter270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchTopCenterFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchTopCenterBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchTopCenter90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchTopCenter180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchTopCenter270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //TopSideArch
    [RotatedVariants(typeof(MortaredLimestoneArchTopSideBlock), typeof(MortaredLimestoneArchTopSide90Block), typeof(MortaredLimestoneArchTopSide180Block), typeof(MortaredLimestoneArchTopSide270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchTopSideFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchTopSideBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchTopSide90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchTopSide180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchTopSide270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //SideArch
    [RotatedVariants(typeof(MortaredLimestoneArchSideBlock), typeof(MortaredLimestoneArchSide90Block), typeof(MortaredLimestoneArchSide180Block), typeof(MortaredLimestoneArchSide270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchSideFormType), typeof(MortaredLimestoneItem))]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchSideBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchSide90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchSide180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredLimestoneArchSide270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
}