// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FormsTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Water;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Tag = Eco.Core.Items.TagAttribute;
    using Eco.World.Color;

    //Custom Forms
    //45
    [RotatedVariants(typeof(MortaredGraniteFourtyFiveBlock), typeof(MortaredGraniteFourtyFive90Block), typeof(MortaredGraniteFourtyFive180Block), typeof(MortaredGraniteFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(Corner45FormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Small45
    [RotatedVariants(typeof(MortaredGraniteSmallFourtyFiveBlock), typeof(MortaredGraniteSmallFourtyFive90Block), typeof(MortaredGraniteSmallFourtyFive180Block), typeof(MortaredGraniteSmallFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(CornerSmall45FormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteSmallFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteSmallFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteSmallFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteSmallFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //45 Wall
    [RotatedVariants(typeof(MortaredGraniteFourtyFiveWallBlock), typeof(MortaredGraniteFourtyFiveWall90Block), typeof(MortaredGraniteFourtyFiveWall180Block), typeof(MortaredGraniteFourtyFiveWall270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(FourtyFiveWallFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteFourtyFiveWallBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteFourtyFiveWall90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteFourtyFiveWall180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteFourtyFiveWall270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Roof45
    [RotatedVariants(typeof(MortaredGraniteRoofFourtyFiveBlock), typeof(MortaredGraniteRoofFourtyFive90Block), typeof(MortaredGraniteRoofFourtyFive180Block), typeof(MortaredGraniteRoofFourtyFive270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(Roof45FormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofFourtyFiveBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofFourtyFive90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofFourtyFive180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofFourtyFive270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Ramps
    [RotatedVariants(typeof(MortaredGraniteRampABlock), typeof(MortaredGraniteRampA90Block), typeof(MortaredGraniteRampA180Block), typeof(MortaredGraniteRampA270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampAFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampABlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampA90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampA180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampA270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredGraniteRampBBlock), typeof(MortaredGraniteRampB90Block), typeof(MortaredGraniteRampB180Block), typeof(MortaredGraniteRampB270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampBFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampBBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampB90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampB180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampB270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredGraniteRampCBlock), typeof(MortaredGraniteRampC90Block), typeof(MortaredGraniteRampC180Block), typeof(MortaredGraniteRampC270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampCFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampCBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampC90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampC180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampC270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredGraniteRampDBlock), typeof(MortaredGraniteRampD90Block), typeof(MortaredGraniteRampD180Block), typeof(MortaredGraniteRampD270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RampDFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampDBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampD90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampD180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRampD270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //RoofRamps
    [RotatedVariants(typeof(MortaredGraniteRoofRampABlock), typeof(MortaredGraniteRoofRampA90Block), typeof(MortaredGraniteRoofRampA180Block), typeof(MortaredGraniteRoofRampA270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampAFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampABlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampA90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampA180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampA270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredGraniteRoofRampBBlock), typeof(MortaredGraniteRoofRampB90Block), typeof(MortaredGraniteRoofRampB180Block), typeof(MortaredGraniteRoofRampB270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampBFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampBBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampB90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampB180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampB270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredGraniteRoofRampCBlock), typeof(MortaredGraniteRoofRampC90Block), typeof(MortaredGraniteRoofRampC180Block), typeof(MortaredGraniteRoofRampC270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampCFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampCBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampC90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampC180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampC270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }
    [RotatedVariants(typeof(MortaredGraniteRoofRampDBlock), typeof(MortaredGraniteRoofRampD90Block), typeof(MortaredGraniteRoofRampD180Block), typeof(MortaredGraniteRoofRampD270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofRampDFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampDBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampD90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampD180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofRampD270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //Roof Edge
    [RotatedVariants(typeof(MortaredGraniteRoofEdgeBlock), typeof(MortaredGraniteRoofEdge90Block), typeof(MortaredGraniteRoofEdge180Block), typeof(MortaredGraniteRoofEdge270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(RoofEdgeFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofEdgeBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofEdge90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofEdge180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteRoofEdge270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //ARCHES
    //TopCenterArch
    [RotatedVariants(typeof(MortaredGraniteArchTopCenterBlock), typeof(MortaredGraniteArchTopCenter90Block), typeof(MortaredGraniteArchTopCenter180Block), typeof(MortaredGraniteArchTopCenter270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchTopCenterFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchTopCenterBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchTopCenter90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchTopCenter180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchTopCenter270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //TopSideArch
    [RotatedVariants(typeof(MortaredGraniteArchTopSideBlock), typeof(MortaredGraniteArchTopSide90Block), typeof(MortaredGraniteArchTopSide180Block), typeof(MortaredGraniteArchTopSide270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchTopSideFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchTopSideBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchTopSide90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchTopSide180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchTopSide270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    //SideArch
    [RotatedVariants(typeof(MortaredGraniteArchSideBlock), typeof(MortaredGraniteArchSide90Block), typeof(MortaredGraniteArchSide180Block), typeof(MortaredGraniteArchSide270Block))]
    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [IsForm(typeof(ArchSideFormType), typeof(MortaredGraniteItem))]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchSideBlock : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchSide90Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchSide180Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

    [Serialized]
    [Wall, Constructed, Solid, BuildRoomMaterialOption]
    [BlockTier(2)]
    [Tag("Constructable")]
    public partial class MortaredGraniteArchSide270Block : Block, IWaterLoggedBlock, IColoredBlock
    { }

}