// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods
{
    // This is an auto-generated file
    // Do not modify this file directly

    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Pipes;
    using Eco.Mods.TechTree;
    using Eco.Shared.Localization;
    using Eco.Shared.Math;
    using Eco.Shared.Serialization;
    using Eco.World.Blocks;
    using Eco.World;
    using Eco.Gameplay.Occupancy;

    [Serialized, Category("Hidden")] // Admins can create this item. Server crash is possible without serialization.
    public class OccupancyInitItemMortared : Item
    {
        static OccupancyInitItemMortared()
        {
            WorldObjectOccupancyMortared.Initialize();
        }
    }

    public static class WorldObjectOccupancyMortared
    {
        public static void Initialize()
        {

            // MortaredShaleDoorObject
            WorldObject.AddOccupancy<MortaredShaleDoorObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0), typeof(BuildingWorldObjectBlock), new Quaternion(0f, 0f, 0f, 1f)),
            new BlockOccupancy(new Vector3i(0, 1, 0), typeof(BuildingWorldObjectBlock), new Quaternion(0f, 0f, 0f, 1f)),
            new BlockOccupancy(new Vector3i(0, 0, -1)),
            new BlockOccupancy(new Vector3i(0, 0, 1)),
            new BlockOccupancy(new Vector3i(0, 1, -1)),
            new BlockOccupancy(new Vector3i(0, 1, 1)),
            });
            // MortaredGneissDoorObject
            WorldObject.AddOccupancy<MortaredGneissDoorObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0), typeof(BuildingWorldObjectBlock), new Quaternion(0f, 0f, 0f, 1f)),
            new BlockOccupancy(new Vector3i(0, 1, 0), typeof(BuildingWorldObjectBlock), new Quaternion(0f, 0f, 0f, 1f)),
            new BlockOccupancy(new Vector3i(0, 0, -1)),
            new BlockOccupancy(new Vector3i(0, 0, 1)),
            new BlockOccupancy(new Vector3i(0, 1, -1)),
            new BlockOccupancy(new Vector3i(0, 1, 1)),
            });
            // MortaredBasaltDoorObject
            WorldObject.AddOccupancy<MortaredBasaltDoorObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0), typeof(BuildingWorldObjectBlock), new Quaternion(0f, 0f, 0f, 1f)),
            new BlockOccupancy(new Vector3i(0, 1, 0), typeof(BuildingWorldObjectBlock), new Quaternion(0f, 0f, 0f, 1f)),
            new BlockOccupancy(new Vector3i(0, 0, -1)),
            new BlockOccupancy(new Vector3i(0, 0, 1)),
            new BlockOccupancy(new Vector3i(0, 1, -1)),
            new BlockOccupancy(new Vector3i(0, 1, 1)),
            });

            // LargeStandingMortaredShaleSignObject
            WorldObject.AddOccupancy<LargeStandingMortaredShaleSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });

            // LargeStandingMortaredGneissSignObject
            WorldObject.AddOccupancy<LargeStandingMortaredGneissSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });

            // LargeStandingMortaredBasaltSignObject
            WorldObject.AddOccupancy<LargeStandingMortaredBasaltSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });


            // LargeHangingMortaredShaleSignObject
            WorldObject.AddOccupancy<LargeHangingMortaredShaleSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });

            // LargeHangingMortaredGneissSignObject
            WorldObject.AddOccupancy<LargeHangingMortaredGneissSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });

            // LargeHangingMortaredBasaltSignObject
            WorldObject.AddOccupancy<LargeHangingMortaredBasaltSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });

            // SmallHangingMortaredShaleSignObject
            WorldObject.AddOccupancy<SmallHangingMortaredShaleSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });

            // SmallHangingMortaredGneissSignObject
            WorldObject.AddOccupancy<SmallHangingMortaredGneissSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });

            // SmallHangingMortaredBasaltSignObject
            WorldObject.AddOccupancy<SmallHangingMortaredBasaltSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });

            // SmallStandingMortaredShaleSignObject
            WorldObject.AddOccupancy<SmallStandingMortaredShaleSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });

            // SmallStandingMortaredGneissSignObject
            WorldObject.AddOccupancy<SmallStandingMortaredGneissSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });

            // SmallStandingMortaredBasaltSignObject
            WorldObject.AddOccupancy<SmallStandingMortaredBasaltSignObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });

            // MortaredShaleFireplaceObject
            WorldObject.AddOccupancy<MortaredShaleFireplaceObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-2, 0, 0)),
            new BlockOccupancy(new Vector3i(-2, 1, 0)),
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });

            // MortaredGneissFireplaceObject
            WorldObject.AddOccupancy<MortaredGneissFireplaceObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-2, 0, 0)),
            new BlockOccupancy(new Vector3i(-2, 1, 0)),
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });

            // MortaredBasaltFireplaceObject
            WorldObject.AddOccupancy<MortaredBasaltFireplaceObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-2, 0, 0)),
            new BlockOccupancy(new Vector3i(-2, 1, 0)),
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });

            // MortaredShaleBenchObject
            WorldObject.AddOccupancy<MortaredShaleBenchObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });
            // MortaredShaleChairObject
            WorldObject.AddOccupancy<MortaredShaleChairObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });
            // MortaredShaleTableObject
            WorldObject.AddOccupancy<MortaredShaleTableObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });

            // MortaredGneissBenchObject
            WorldObject.AddOccupancy<MortaredGneissBenchObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });
            // MortaredGneissChairObject
            WorldObject.AddOccupancy<MortaredGneissChairObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });
            // MortaredGneissTableObject
            WorldObject.AddOccupancy<MortaredGneissTableObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });

            // MortaredBasaltBenchObject
            WorldObject.AddOccupancy<MortaredBasaltBenchObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(-1, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });
            // MortaredBasaltChairObject
            WorldObject.AddOccupancy<MortaredBasaltChairObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            });
            // MortaredBasaltTableObject
            WorldObject.AddOccupancy<MortaredBasaltTableObject>(new List<BlockOccupancy>(){
            new BlockOccupancy(new Vector3i(-1, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            });
        }
    }
}
