
// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from BenefitTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Mods.TechTree;
    using Eco.Shared.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;

    /// <summary>
    /// <para>Server side talent group definition for "ToolStrength".</para>
    /// <para>More information about TalentGroup objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Skills.TalentGroup.html</para>
    /// </summary>
    [Serialized]
    [LocDisplayName("Close Encounters")]
    [LocDescription("Increases the damage of machetes by 0.8, making them viable hunting tools.")]
    public partial class HuntingMacheteStrengthTalentGroup : TalentGroup
    {
        public HuntingMacheteStrengthTalentGroup()
        {
            Talents = new Type[]
            {
                typeof(MacheteStrengthTalent),
            };
            this.OwningSkill = typeof(HuntingSkill);
            this.Level = 0;
        }
    }

    [Serialized]
    public partial class MacheteStrengthTalent : ToolStrengthTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(HuntingMacheteStrengthTalentGroup); } }
        public MacheteStrengthTalent()
        {
            this.Value = 0.8f;
        }
    }
}
