﻿// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using Eco.Gameplay.Blocks;
    using Eco.Shared.Localization;
    using Eco.World.Blocks;

    [NextRamp(typeof(RoofRampBFormType), 0)]
    public partial class RoofRampAFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "RoofRampA";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("Roof Ramp A");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("Roof Ramp A");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(RampsFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 101;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    [NextRamp(typeof(RoofRampCFormType), 0)]
    public partial class RoofRampBFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "RoofRampB";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("Roof Ramp B");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("Roof Ramp B");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(RampsFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 102;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    [NextRamp(typeof(RoofRampDFormType), 0)]
    public partial class RoofRampCFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "RoofRampC";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("Roof Ramp C");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("Roof Ramp C");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(RampsFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 103;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    [NextRamp(typeof(RoofRampAFormType), 1)]
    public partial class RoofRampDFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "RoofRampD";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("Roof Ramp D");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("Roof Ramp D");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(RampsFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 104;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

    public partial class RoofEdgeFormType : FormType
    {
        /// <summary>Basic name of the block form type.</summary>
        public override string Name => "RoofEdge";
        /// <summary>The plural localization name for the block form type.</summary>
        public override LocString DisplayName => Localizer.DoStr("Roof Edge");
        /// <summary>The tooltip description for the block form type.</summary>
        public override LocString DisplayDescription => Localizer.DoStr("Roof Edge");
        /// <summary>The block FormGroup this form type belongs to</summary>
        public override Type GroupType => typeof(RampsFormGroup);
        /// <summary>Defines the sort order used by this block form type</summary>
        public override int SortOrder => 105;
        /// <summary>Defines the minimum hammer tier for this block form type</summary>
        public override int MinTier => 1;
    }

}
